{% set version = "1.2.5" %}
{% set sha256 = "94ec8c36bd6628a11de9014346692daeeef99b3b7bae28cef30c7490bbcb2d72" %}

{% set suitesparse_version = "5.7.2" %}
{% set suitesparse_sha256 = "fe3bc7c3bd1efdfa5cffffb5cebf021ff024c83b5daf0ab445429d3d741bd3ad" %}

package:
  name: cvxopt
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/drtimothyaldendavis/suitesparse/archive/v{{ suitesparse_version }}.tar.gz  # [win]
    sha256: {{ suitesparse_sha256 }}  # [win]
    folder: suitesparse  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - setuptools
    - mkl-devel {{ mkl }}  # [blas_impl == "mkl"]
    - openblas-devel  # [blas_impl == "openblas"]
    - gsl  # [unix]
    - fftw  # [unix]
    - dsdp  # [unix]
    - glpk
    - suitesparse    # [unix]

  run:
    - python

test:
  imports:
    - cvxopt
  source_files:
    - tests/*
    - examples/*

about:
  home: http://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
