{% set version = "1.2.0" %}
{% set sha256 = "3296c9d49b7dcb894b20db5d7d1c1a443912b4d82358e03f836575e8398e0d60" %}

{% set suitesparse_version = "5.3.0" %}
{% set suitesparse_sha256 = "90e69713d8c454da5a95a839aea5d97d8d03d00cc1f667c4bdfca03f640f963d" %}

package:
  name: cvxopt
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-{{ suitesparse_version }}.tar.gz  # [win]
    sha256: {{ suitesparse_sha256 }}
    folder: SuiteSparse

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - c99-to-c89          # [win and vc<14]
  host:
    - python
    - setuptools
    - mkl-devel  # [blas_impl == "mkl"]
    - openblas-devel  # [blas_impl == "openblas"]
    - gsl  # [unix]
    - fftw  # [unix]
    - glpk
    - suitesparse    # [unix]

  run:
    - python

test:
  imports:
    - cvxopt
  source_files:
    - tests/*
    - examples/*

about:
  home: http://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
